SELECT D.UUID AS i,  UPPER(TD.VALUE) AS v, E.EXPRESSION AS e,
AC.INTERNALCODE AS c,
D.INTERNALCODEDATATYPE as d,
CASE 
    WHEN d.UUIDADVANCEDSEARCHCATEGORY is not null
        THEN UPPER(TD.VALUE) + ' ' + (select UPPER(VALUE) from MP_TRANSLATION tr where tr.UUIDLABEL = AC.UUIDLABEL and tr.UUIDLANGUAGE='DC376CF4-1ABC-4F91-8F48-9A5DB68A4E8E')
    ELSE UPPER(TD.VALUE)
END as t
FROM MP_DICTIONARY D
JOIN MP_EXPRESSION E
ON D.UUIDEXPRESSION = E.UUID
JOIN MP_TRANSLATION TD
ON D.UUIDLABEL = TD.UUIDLABEL
left JOIN MP_ADVANCEDSEARCHCATEGORY AC
ON D.UUIDADVANCEDSEARCHCATEGORY = AC.UUID
WHERE TD.UUIDLANGUAGE ='DC376CF4-1ABC-4F91-8F48-9A5DB68A4E8E'